d3d12: fix constexpr compatability with clang
This `static constexpr` fails to compile with clang in `-std=c++17` mode due to:

```
error: constexpr variable 'kD3D12PromotableReadOnlyStates' must be initialized by a constant expression
```

I'm not extremely familiar with constexpr to know if there is another better
fix for this, or if this is just some difference between clang and msvc, but
having this just be `static` doesn't seem too harmful and gets zig/clang
compatability which I'd love.

Signed-off-by: Stephen Gutekanst <stephen@hexops.com>